---
  redis:
    host: localhost
    port: 6379
    channel: monitor
    listen_for: monitor
  node:
    port: 3001
  services:
    - 
      name: ssh
      port: 22
    - 
      name: http
      port: 80
